--------------------------------------------------------
--  DDL for Table BANK_ACCOUNTS
--------------------------------------------------------

  CREATE TABLE "BANKUSER"."BANK_ACCOUNTS" 
   (	"ACCOUNT_NUM" VARCHAR2(20 BYTE), 
	"BALANCE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BANK_ACCOUNTS_ITEMS
--------------------------------------------------------

  CREATE TABLE "BANKUSER"."BANK_ACCOUNTS_ITEMS" 
   (	"CLIENT_ID" VARCHAR2(10 BYTE), 
	"ACCOUNT_NUM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BANK_BANKNOTES
--------------------------------------------------------

  CREATE TABLE "BANKUSER"."BANK_BANKNOTES" 
   (	"TYPE" NUMBER(5,0), 
	"COUNT" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BANK_CARDS
--------------------------------------------------------

  CREATE TABLE "BANKUSER"."BANK_CARDS" 
   (	"CARD_NUM" VARCHAR2(16 BYTE), 
	"PIN" VARCHAR2(4 BYTE), 
	"VALID_DATE" DATE, 
	"ACCOUNT_NUM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BANK_CLIENTS
--------------------------------------------------------

  CREATE TABLE "BANKUSER"."BANK_CLIENTS" 
   (	"CLIENT_ID" VARCHAR2(10 BYTE), 
	"FIRSTNAME" VARCHAR2(20 BYTE), 
	"LASTNAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
REM INSERTING into BANKUSER.BANK_ACCOUNTS
SET DEFINE OFF;
Insert into BANKUSER.BANK_ACCOUNTS (ACCOUNT_NUM,BALANCE) values ('1425368461','30000,1');
Insert into BANKUSER.BANK_ACCOUNTS (ACCOUNT_NUM,BALANCE) values ('9283746155','0');
Insert into BANKUSER.BANK_ACCOUNTS (ACCOUNT_NUM,BALANCE) values ('6482937364','550000,76');
REM INSERTING into BANKUSER.BANK_ACCOUNTS_ITEMS
SET DEFINE OFF;
Insert into BANKUSER.BANK_ACCOUNTS_ITEMS (CLIENT_ID,ACCOUNT_NUM) values ('019837','1425368461');
REM INSERTING into BANKUSER.BANK_BANKNOTES
SET DEFINE OFF;
Insert into BANKUSER.BANK_BANKNOTES (TYPE,COUNT) values ('100','1000');
Insert into BANKUSER.BANK_BANKNOTES (TYPE,COUNT) values ('200','1000');
Insert into BANKUSER.BANK_BANKNOTES (TYPE,COUNT) values ('500','2000');
Insert into BANKUSER.BANK_BANKNOTES (TYPE,COUNT) values ('1000','2000');
Insert into BANKUSER.BANK_BANKNOTES (TYPE,COUNT) values ('2000','1000');
Insert into BANKUSER.BANK_BANKNOTES (TYPE,COUNT) values ('5000','2500');
REM INSERTING into BANKUSER.BANK_CARDS
SET DEFINE OFF;
Insert into BANKUSER.BANK_CARDS (CARD_NUM,PIN,VALID_DATE,ACCOUNT_NUM) values ('4201764522335463','1010',to_date('16.04.21','DD.MM.RR'),'1425368461');
REM INSERTING into BANKUSER.BANK_CLIENTS
SET DEFINE OFF;
Insert into BANKUSER.BANK_CLIENTS (CLIENT_ID,FIRSTNAME,LASTNAME) values ('019837','IVANOV','PETR');
Insert into BANKUSER.BANK_CLIENTS (CLIENT_ID,FIRSTNAME,LASTNAME) values ('201983','FEDOROV','KIRILL');
Insert into BANKUSER.BANK_CLIENTS (CLIENT_ID,FIRSTNAME,LASTNAME) values ('092878','TUTYSHEVA','MARIYA');
  
--------------------------------------------------------
--  DDL for Index BANK_CLIENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BANKUSER"."BANK_CLIENTS_PK" ON "BANKUSER"."BANK_CLIENTS" ("CLIENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
--------------------------------------------------------
--  DDL for Index BANK_CARDS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BANKUSER"."BANK_CARDS_PK" ON "BANKUSER"."BANK_CARDS" ("CARD_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
--------------------------------------------------------
--  Ref Constraints for Table BANK_ACCOUNTS_ITEMS
--------------------------------------------------------

  ALTER TABLE "BANKUSER"."BANK_ACCOUNTS_ITEMS" ADD CONSTRAINT "BANK_ACCOUNTS_ITEMS_FK1" FOREIGN KEY ("ACCOUNT_NUM")
	  REFERENCES "BANKUSER"."BANK_ACCOUNTS" ("ACCOUNT_NUM") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BANKUSER"."BANK_ACCOUNTS_ITEMS" ADD CONSTRAINT "BANK_ACCOUNTS_ITEMS_FK2" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "BANKUSER"."BANK_CLIENTS" ("CLIENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BANK_CARDS
--------------------------------------------------------

  ALTER TABLE "BANKUSER"."BANK_CARDS" ADD CONSTRAINT "BANK_CARDS_FK1" FOREIGN KEY ("ACCOUNT_NUM")
	  REFERENCES "BANKUSER"."BANK_ACCOUNTS" ("ACCOUNT_NUM") ON DELETE CASCADE ENABLE;
	  
--------------------------------------------------------
--  Constraints for Table BANK_BANKNOTES
--------------------------------------------------------

  ALTER TABLE "BANKUSER"."BANK_BANKNOTES" MODIFY ("TYPE" NOT NULL ENABLE);
  
--------------------------------------------------------
--  Constraints for Table BANK_CARDS
--------------------------------------------------------

  ALTER TABLE "BANKUSER"."BANK_CARDS" MODIFY ("ACCOUNT_NUM" NOT NULL ENABLE);
  ALTER TABLE "BANKUSER"."BANK_CARDS" ADD CONSTRAINT "BANK_CARDS_PK" PRIMARY KEY ("CARD_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BANKUSER"."BANK_CARDS" MODIFY ("VALID_DATE" NOT NULL ENABLE);
  ALTER TABLE "BANKUSER"."BANK_CARDS" MODIFY ("PIN" NOT NULL ENABLE);
  ALTER TABLE "BANKUSER"."BANK_CARDS" MODIFY ("CARD_NUM" NOT NULL ENABLE);
  
--------------------------------------------------------
--  Constraints for Table BANK_ACCOUNTS
--------------------------------------------------------

  ALTER TABLE "BANKUSER"."BANK_ACCOUNTS" ADD CONSTRAINT "ACCOUNTS_PK" PRIMARY KEY ("ACCOUNT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BANKUSER"."BANK_ACCOUNTS" MODIFY ("ACCOUNT_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BANK_CLIENTS
--------------------------------------------------------

  ALTER TABLE "BANKUSER"."BANK_CLIENTS" ADD CONSTRAINT "BANK_CLIENTS_PK" PRIMARY KEY ("CLIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BANKUSER"."BANK_CLIENTS" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "BANKUSER"."BANK_CLIENTS" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "BANKUSER"."BANK_CLIENTS" MODIFY ("CLIENT_ID" NOT NULL ENABLE);
  
--------------------------------------------------------
--  Constraints for Table BANK_ACCOUNTS_ITEMS
--------------------------------------------------------

  ALTER TABLE "BANKUSER"."BANK_ACCOUNTS_ITEMS" MODIFY ("ACCOUNT_NUM" NOT NULL ENABLE);
  ALTER TABLE "BANKUSER"."BANK_ACCOUNTS_ITEMS" MODIFY ("CLIENT_ID" NOT NULL ENABLE);